// SIBClient.swift — Phase 2A
// async/await REST client for SIB v0.2. All network calls go through here.

import Foundation

enum SIBClientError: LocalizedError {
    case notConfigured
    case invalidURL(String)
    case networkError(Error)
    case httpError(Int, String)
    case decodingError(Error)

    var errorDescription: String? {
        switch self {
        case .notConfigured:          return "SIB URL not configured. Go to Settings."
        case .invalidURL(let u):      return "Invalid URL: \(u)"
        case .networkError(let e):    return "Network error: \(e.localizedDescription)"
        case .httpError(let c, let m): return "SIB error \(c): \(m)"
        case .decodingError(let e):   return "Bad response: \(e.localizedDescription)"
        }
    }

    // #75: short, actionable copy for display in the UI. errorDescription
    // above stays as-is for logs/debugging (it leaks raw status text/server
    // messages, which isn't useful or reassuring to an Author/Operator).
    var userFacingMessage: String {
        switch self {
        case .notConfigured:
            return "Server not set up yet. Open Settings and enter the SIB URL."
        case .invalidURL:
            return "That server address looks invalid. Check it in Settings."
        case .networkError(let e):
            if (e as? URLError)?.code == .timedOut {
                return "Upload timed out — check your connection and try again."
            }
            return "Couldn't reach the server. Check your connection and try again."
        case .httpError(let c, _) where c >= 500:
            return "Server is having trouble right now. Try again in a moment."
        case .httpError(413, _):
            return "That upload was too large for the server to accept."
        case .httpError:
            return "The server rejected that request. Try again, and reach out if it keeps happening."
        case .decodingError:
            return "Got an unexpected response from the server. Try again."
        }
    }
}

/// Maps any error (SIBClientError or otherwise) to short, actionable copy
/// for display in alerts/toasts, instead of a raw localizedDescription.
func friendlyMessage(for error: Error) -> String {
    if let sibError = error as? SIBClientError { return sibError.userFacingMessage }
    if (error as? URLError)?.code == .timedOut {
        return "Request timed out — check your connection and try again."
    }
    return "Something went wrong: \(error.localizedDescription)"
}

final class SIBClient {

    private let settings: AppSettings
    private let session: URLSession

    init(settings: AppSettings) {
        self.settings = settings
        let config = URLSessionConfiguration.default
        // #73: 20s default covers ordinary CRUD calls (tags, sessions) so a
        // dropped connection fails fast instead of hanging for a minute.
        // The few genuinely heavy operations (training upload, validate-all,
        // world-map transfer) override this per-request below — see
        // makeRequest(timeout:) and the explicit overrides in
        // trainPassState/validateAll/uploadWorldMap/fetchWorldMap.
        config.timeoutIntervalForRequest = 20
        self.session = URLSession(configuration: config)
    }

    // ── Connection ────────────────────────────────────────────────────────────

    func testConnection() async throws {
        _ = try await get([Anchor].self, path: "/anchors")
    }

    // ── Anchors ───────────────────────────────────────────────────────────────

    /// List all anchors — used by AnchorDirectoryView.
    func fetchAnchors() async throws -> [Anchor] {
        try await get([Anchor].self, path: "/anchors")
    }

    func fetchAnchor(id: String) async throws -> Anchor {
        try await get(Anchor.self, path: "/anchors/\(id)")
    }

    /// Phase 2.5 G1 — check whether an anchor has enough trained pass-states for Operator use.
    func fetchAnchorReadiness(id: String) async throws -> AnchorReadiness {
        try await get(AnchorReadiness.self, path: "/anchors/\(id)/readiness")
    }

    func createAnchor(_ req: CreateAnchorRequest) async throws -> Anchor {
        try await post(Anchor.self, path: "/anchors", body: req)
    }

    /// Delete an anchor and all its tags + pass-states (cascade).
    func deleteAnchor(id: String) async throws {
        try await delete(path: "/anchors/\(id)")
    }

    /// Fetch the canonical QR PNG generated by the server at anchor creation.
    /// Both the iOS app (QRGeneratorView) and the portal display this image so
    /// all clients show the identical pixel pattern regardless of QR library.
    func fetchAnchorQRImage(anchorId: String) async throws -> Data {
        let req = try makeRequest(method: "GET", path: "/anchors/\(anchorId)/qrimage")
        let (data, response): (Data, URLResponse)
        do { (data, response) = try await session.data(for: req) }
        catch { throw SIBClientError.networkError(error) }
        if let http = response as? HTTPURLResponse, !(200...299).contains(http.statusCode) {
            let msg = (try? JSONDecoder().decode(APIError.self, from: data))?.error ?? "HTTP \(http.statusCode)"
            throw SIBClientError.httpError(http.statusCode, msg)
        }
        return data
    }

    /// Upload a serialised ARWorldMap (NSKeyedArchiver binary plist) for an anchor.
    /// The server stores it so subsequent sessions can relocalize into the same
    /// feature-point cloud, giving scan-position-independent tag placement.
    func uploadWorldMap(anchorId: String, data: Data) async throws {
        var req = try makeRequest(method: "POST", path: "/anchors/\(anchorId)/worldmap")
        req.timeoutInterval = 90 // #73: large binary payload, needs more than the 20s CRUD default
        req.setValue("application/octet-stream", forHTTPHeaderField: "Content-Type")
        req.httpBody = data
        let (_, response): (Data, URLResponse)
        do { (_, response) = try await session.data(for: req) }
        catch { throw SIBClientError.networkError(error) }
        if let http = response as? HTTPURLResponse, !(200...299).contains(http.statusCode) {
            throw SIBClientError.httpError(http.statusCode, "World map upload failed (\(http.statusCode))")
        }
    }

    /// Download a previously stored ARWorldMap binary for an anchor.
    /// Returns nil (does NOT throw) on 404 — meaning no map has been saved yet
    /// and the caller should start a fresh session instead.
    func fetchWorldMap(anchorId: String) async throws -> Data? {
        var req = try makeRequest(method: "GET", path: "/anchors/\(anchorId)/worldmap")
        req.timeoutInterval = 45 // #73: larger-than-CRUD binary download
        let (data, response): (Data, URLResponse)
        do { (data, response) = try await session.data(for: req) }
        catch { throw SIBClientError.networkError(error) }
        guard let http = response as? HTTPURLResponse else { return nil }
        if http.statusCode == 404 { return nil }            // no map stored yet — normal first-session case
        if !(200...299).contains(http.statusCode) {
            throw SIBClientError.httpError(http.statusCode, "World map download failed (\(http.statusCode))")
        }
        return data
    }

    // ── Tags ──────────────────────────────────────────────────────────────────

    /// Fetch tags for an anchor, optionally filtered to a specific Inspection Set.
    func fetchTags(anchorId: String, groupId: String? = nil) async throws -> [Tag] {
        var path = "/tags?anchorId=\(anchorId)"
        if let gid = groupId { path += "&groupId=\(gid)" }
        return try await get([Tag].self, path: path)
    }

    func createTag(_ req: CreateTagRequest) async throws -> Tag {
        try await post(Tag.self, path: "/tags", body: req)
    }

    func updateTag(id: String, req: UpdateTagRequest) async throws -> Tag {
        try await patch(Tag.self, path: "/tags/\(id)", body: req)
    }

    func deleteTag(id: String) async throws {
        try await delete(path: "/tags/\(id)")
    }

    func deleteAllTags(anchorId: String) async throws {
        try await delete(path: "/tags?anchorId=\(anchorId)")
    }

    // ── Tag Groups (Inspection Sets) ──────────────────────────────────────────

    func fetchTagGroups(anchorId: String) async throws -> [TagGroup] {
        try await get([TagGroup].self, path: "/tag-groups?anchorId=\(anchorId)")
    }

    func createTagGroup(_ req: CreateTagGroupRequest) async throws -> TagGroup {
        try await post(TagGroup.self, path: "/tag-groups", body: req)
    }

    func updateTagGroup(id: String, req: UpdateTagGroupRequest) async throws -> TagGroup {
        try await patch(TagGroup.self, path: "/tag-groups/\(id)", body: req)
    }

    func deleteTagGroup(id: String) async throws {
        try await delete(path: "/tag-groups/\(id)")
    }

    // ── Pass-state ────────────────────────────────────────────────────────────

    func trainPassState(_ req: CreatePassStateRequest) async throws {
        struct R: Codable { let id: String }
        // #73: multi-image honeycomb upload is the largest payload the app
        // sends — the 20s CRUD default isn't enough on a slow connection.
        _ = try await post(R.self, path: "/perception/train", body: req, timeout: 90)
    }

    func fetchPassState(tagId: String) async throws -> PassState {
        try await get(PassState.self, path: "/perception/pass-state/\(tagId)")
    }

    // ── Validation ────────────────────────────────────────────────────────────

    func validateAll(_ req: BatchValidateRequest) async throws -> AnchorValidationResult {
        // #73: validate-all runs SSIM/patch-grid scoring across many tags —
        // kept at the previous 60s budget rather than the new 20s CRUD default.
        try await post(AnchorValidationResult.self, path: "/perception/validate-all", body: req, timeout: 60)
    }

    // ── Sessions ──────────────────────────────────────────────────────────────

    func createSession(userId: String, assetId: String) async throws -> SIBSession {
        try await post(SIBSession.self, path: "/sessions",
                       body: CreateSessionRequest(userId: userId, assetId: assetId))
    }

    // ── Phase 4: Inspection reporting ────────────────────────────────────────

    /// Submit the full inspection report on End Session.
    /// Patches the existing SIBSession record with ownerName, per-tag results,
    /// overall status, end time, and duration.
    func submitReport(sessionId: String, report: SubmitReportRequest) async throws -> SIBSession {
        try await patch(SIBSession.self, path: "/sessions/\(sessionId)/report", body: report)
    }

    /// Upload one evidence image for a tag.
    /// Called per-tag when the Operator taps "Tag Inspected".
    /// Returns the `imagePath` (filename) stored on the server.
    func uploadEvidence(sessionId: String, tagId: String, request: UploadEvidenceRequest) async throws -> EvidenceUploadResponse {
        try await post(EvidenceUploadResponse.self,
                       path: "/sessions/\(sessionId)/evidence/\(tagId)",
                       body: request,
                       timeout: 30)
    }

    // ── Loc-Tags (Phase 2) ───────────────────────────────────────────────────

    /// Author: create a Loc-Tag during a Gemba audit walk.
    /// Includes optional reference image (base64 JPEG) — use a 30s timeout for the upload.
    func createLocTag(_ req: CreateLocTagRequest) async throws -> LocTag {
        try await post(LocTag.self, path: "/loc-tags", body: req, timeout: 30)
    }

    /// Fetch all Loc-Tags for an anchor, sorted by author-defined order.
    func fetchLocTags(anchorId: String) async throws -> [LocTag] {
        try await get([LocTag].self, path: "/loc-tags?anchorId=\(anchorId)")
    }

    /// Fetch the reference or completion photo for a Loc-Tag by its stored filename.
    func fetchLocTagImage(filename: String) async throws -> Data {
        let req = try makeRequest(method: "GET", path: "/loc-tags/image/\(filename)")
        let (data, response): (Data, URLResponse)
        do { (data, response) = try await session.data(for: req) }
        catch { throw SIBClientError.networkError(error) }
        if let http = response as? HTTPURLResponse, !(200...299).contains(http.statusCode) {
            let msg = (try? JSONDecoder().decode(APIError.self, from: data))?.error ?? "HTTP \(http.statusCode)"
            throw SIBClientError.httpError(http.statusCode, msg)
        }
        return data
    }

    /// Operator: submit a completion record for a Loc-Tag visit.
    /// Includes optional completion photo — 30s timeout.
    func submitLocTagCompletion(
        locTagId: String,
        req: SubmitLocTagCompletionRequest
    ) async throws -> LocTagCompletion {
        try await post(LocTagCompletion.self,
                       path: "/loc-tags/\(locTagId)/completion",
                       body: req,
                       timeout: 30)
    }

    /// Fetch all completion records for a Loc-Tag (newest last).
    func fetchLocTagCompletions(locTagId: String) async throws -> [LocTagCompletion] {
        try await get([LocTagCompletion].self, path: "/loc-tags/\(locTagId)/completions")
    }

    /// Author: update mutable fields of an existing Loc-Tag.
    func updateLocTag(id: String, req: UpdateLocTagRequest) async throws -> LocTag {
        try await patch(LocTag.self, path: "/loc-tags/\(id)", body: req)
    }

    /// Author: delete a Loc-Tag and all its completion records.
    func deleteLocTag(id: String) async throws {
        try await delete(path: "/loc-tags/\(id)")
    }

    // ── iLOTO (docs/ILOTO.md) ────────────────────────────────────────────────
    // Status is DERIVED by the server from the append-only event log — the
    // client never computes lock state locally.

    /// Author: define an isolation point (position placed in AR on device).
    func createLotoPoint(_ req: CreateLotoPointRequest) async throws -> LotoPoint {
        try await post(LotoPoint.self, path: "/loto/points", body: req)
    }

    func fetchLotoPoints(anchorId: String) async throws -> [LotoPoint] {
        try await get([LotoPoint].self, path: "/loto/points?anchorId=\(anchorId)")
    }

    /// Author: update a point — label/circuit, model assignment, or the AR
    /// placement (offsets/rotation from the adjust gestures).
    func updateLotoPoint(id: String, req: UpdateLotoPointRequest) async throws -> LotoPoint {
        try await patch(LotoPoint.self, path: "/loto/points/\(id)", body: req)
    }

    /// Author: delete a CLEAR point (server refuses with 409 while locked).
    /// The point's event history is kept server-side for audit.
    func deleteLotoPoint(id: String) async throws {
        try await delete(path: "/loto/points/\(id)")
    }

    /// Record an apply / remove / override-remove. The server validates the
    /// checklist, one-lock-one-person and override conditions — a 4xx means
    /// the flow tried to skip a required step.
    func submitLotoEvent(_ req: CreateLotoEventRequest) async throws -> LotoEventResponse {
        try await post(LotoEventResponse.self, path: "/loto/events", body: req, timeout: 30)
    }

    /// Audit trail for an anchor (newest first).
    func fetchLotoEvents(anchorId: String) async throws -> [LotoEvent] {
        try await get([LotoEvent].self, path: "/loto/events?anchorId=\(anchorId)")
    }

    /// Evidence photo for an event (photoPath from the event record).
    func fetchLotoEventPhoto(filename: String) async throws -> Data {
        let req = try makeRequest(method: "GET", path: "/loto/events/photo/\(filename)")
        let (data, response): (Data, URLResponse)
        do { (data, response) = try await session.data(for: req) }
        catch { throw SIBClientError.networkError(error) }
        if let http = response as? HTTPURLResponse, !(200...299).contains(http.statusCode) {
            let msg = (try? JSONDecoder().decode(APIError.self, from: data))?.error ?? "HTTP \(http.statusCode)"
            throw SIBClientError.httpError(http.statusCode, msg)
        }
        return data
    }

    /// Panel status: per-point states + red/yellow counts (hub banner).
    func fetchLotoStatus(anchorId: String) async throws -> LotoAnchorStatus {
        try await get(LotoAnchorStatus.self, path: "/loto/status?anchorId=\(anchorId)")
    }

    /// My active locks across ALL anchors (My LOTO / shift-end check).
    func fetchMyLoto(userId: String) async throws -> [MyLotoEntry] {
        let encoded = userId.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed) ?? userId
        return try await get([MyLotoEntry].self, path: "/loto/my?userId=\(encoded)")
    }

    /// Training questions — answers withheld; grading is server-side.
    func fetchLotoQuiz() async throws -> LotoQuizPayload {
        try await get(LotoQuizPayload.self, path: "/loto/quiz")
    }

    /// Submit answers → graded result + certification record (pass or fail).
    func submitLotoQuiz(_ req: SubmitLotoQuizRequest) async throws -> SubmitLotoQuizResult {
        try await post(SubmitLotoQuizResult.self, path: "/loto/quiz/submit", body: req, timeout: 30)
    }

    /// Latest flow map for a panel, or nil when none has been drawn yet.
    func fetchLotoMap(anchorId: String) async throws -> LotoMap? {
        do {
            return try await get(LotoMap.self, path: "/loto/map?anchorId=\(anchorId)")
        } catch SIBClientError.httpError(404, _) {
            return nil
        }
    }

    /// Save a new version of the panel's flow map (previous versions kept).
    func saveLotoMap(_ req: SaveLotoMapRequest) async throws -> LotoMap {
        try await post(LotoMap.self, path: "/loto/map", body: req, timeout: 30)
    }

    /// Delete the panel's flow map (all versions).
    func deleteLotoMap(anchorId: String) async throws {
        try await delete(path: "/loto/map?anchorId=\(anchorId)")
    }

    /// Certification history for a user, newest first (head = current).
    func fetchLotoCertifications(userId: String) async throws -> [LotoCertification] {
        let encoded = userId.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed) ?? userId
        return try await get([LotoCertification].self, path: "/loto/certifications?userId=\(encoded)")
    }

    // ── Loc-Tag ARWorldMap (Phase 2) ─────────────────────────────────────────

    /// Author: save the ARWorldMap captured at the end of a Gemba audit walk.
    /// Optionally includes a reference photo (captured at first tag save) so
    /// Operators can visually confirm their starting position during re-localization.
    /// Body is base64-encoded to fit JSON transport; 90s timeout for large maps.
    func uploadLocTagWorldMap(anchorId: String, mapData: Data, referencePhoto: Data? = nil) async throws {
        struct UploadResponse: Decodable { let anchorId: String; let sizeBytes: Int; let refPhotoSaved: Bool }
        let req = WorldMapUploadRequest(anchorId: anchorId, mapData: mapData, referencePhoto: referencePhoto)
        _ = try await post(UploadResponse.self, path: "/worldmap/upload", body: req, timeout: 90)
    }

    /// Download the reference photo for a Loc-Tag anchor.
    /// Returns nil on 404 (no photo was saved — older anchors or Author skipped it).
    func fetchLocTagReferencePhoto(anchorId: String) async throws -> Data? {
        let req = try makeRequest(method: "GET", path: "/worldmap/\(anchorId)/reference-photo")
        let (data, response): (Data, URLResponse)
        do { (data, response) = try await session.data(for: req) }
        catch { throw SIBClientError.networkError(error) }
        guard let http = response as? HTTPURLResponse else { return nil }
        if http.statusCode == 404 { return nil }
        if !(200...299).contains(http.statusCode) {
            throw SIBClientError.httpError(http.statusCode, "Reference photo download failed (\(http.statusCode))")
        }
        return data
    }

    /// Operator: download the ARWorldMap for an anchor to re-localize.
    /// Returns nil on 404 (no map saved yet — fresh session).
    /// The response is raw binary (application/octet-stream), not a JSON envelope.
    func fetchLocTagWorldMap(anchorId: String) async throws -> Data? {
        var req = try makeRequest(method: "GET", path: "/worldmap/\(anchorId)")
        req.timeoutInterval = 45
        let (data, response): (Data, URLResponse)
        do { (data, response) = try await session.data(for: req) }
        catch { throw SIBClientError.networkError(error) }
        guard let http = response as? HTTPURLResponse else { return nil }
        if http.statusCode == 404 { return nil }
        if !(200...299).contains(http.statusCode) {
            throw SIBClientError.httpError(http.statusCode, "World map download failed (\(http.statusCode))")
        }
        return data
    }

    // ── AR OMS — Guides ──────────────────────────────────────────────────────

    /// Fetch guides for an anchor.
    /// `includeUnpublished: true` → Author view (all guides inc. drafts).
    /// `includeUnpublished: false` → Operator view (published only).
    func fetchGuides(anchorId: String, includeUnpublished: Bool = false) async throws -> [ARGuide] {
        let suffix = includeUnpublished ? "&all=true" : ""
        return try await get([ARGuide].self, path: "/guides?anchorId=\(anchorId)\(suffix)")
    }

    /// Author: create a new Guide (always starts as draft — published=false).
    func createGuide(_ req: CreateARGuideRequest) async throws -> ARGuide {
        try await post(ARGuide.self, path: "/guides", body: req)
    }

    /// Author: update Guide name, description, or published flag.
    func updateGuide(id: String, req: UpdateARGuideRequest) async throws -> ARGuide {
        try await patch(ARGuide.self, path: "/guides/\(id)", body: req)
    }

    /// Author: cascade-delete a Guide and all its Steps.
    func deleteGuide(id: String) async throws {
        try await delete(path: "/guides/\(id)")
    }

    // ── AR OMS — Steps ────────────────────────────────────────────────────────

    /// Fetch all steps for a guide, sorted by sequenceNumber (ascending).
    func fetchGuideSteps(guideId: String) async throws -> [GuideStep] {
        try await get([GuideStep].self, path: "/guides/\(guideId)/steps")
    }

    /// Author: add a step to a Guide.
    /// Use the `CreateGuideStepRequest(image:)` convenience init to include a photo.
    /// 30s timeout to accommodate base64 image payloads.
    func createGuideStep(guideId: String, req: CreateGuideStepRequest) async throws -> GuideStep {
        try await post(GuideStep.self, path: "/guides/\(guideId)/steps", body: req, timeout: 30)
    }

    /// Author: update a step's text, sequence, or image.
    func updateGuideStep(guideId: String, stepId: String, req: UpdateGuideStepRequest) async throws -> GuideStep {
        try await patch(GuideStep.self, path: "/guides/\(guideId)/steps/\(stepId)", body: req)
    }

    /// Author: delete a single step.
    func deleteGuideStep(guideId: String, stepId: String) async throws {
        try await delete(path: "/guides/\(guideId)/steps/\(stepId)")
    }

    /// Fetch a step's attached image by its stored filename.
    /// Returns raw JPEG Data — display via UIImage(data:).
    func fetchGuideStepImage(filename: String) async throws -> Data {
        let req = try makeRequest(method: "GET", path: "/guides/step-image/\(filename)")
        let (data, response): (Data, URLResponse)
        do { (data, response) = try await session.data(for: req) }
        catch { throw SIBClientError.networkError(error) }
        if let http = response as? HTTPURLResponse, !(200...299).contains(http.statusCode) {
            let msg = (try? JSONDecoder().decode(APIError.self, from: data))?.error ?? "HTTP \(http.statusCode)"
            throw SIBClientError.httpError(http.statusCode, msg)
        }
        return data
    }

    // ── AR OMS — Guide Sessions ───────────────────────────────────────────────

    /// Operator: submit a completed guide session atomically at sign-off.
    /// The entire session (step completions, duration, signed-off name) is sent in one call.
    func submitGuideSession(_ req: CreateARGuideSessionRequest) async throws -> ARGuideSession {
        try await post(ARGuideSession.self, path: "/guide-sessions", body: req)
    }

    /// Fetch sessions for an anchor or guide (or both).
    /// Returns records newest-first.
    func fetchGuideSessions(anchorId: String? = nil, guideId: String? = nil) async throws -> [ARGuideSession] {
        var parts: [String] = []
        if let a = anchorId { parts.append("anchorId=\(a)") }
        if let g = guideId  { parts.append("guideId=\(g)") }
        let query = parts.joined(separator: "&")
        return try await get([ARGuideSession].self, path: "/guide-sessions?\(query)")
    }

    // ── Live Guide Session (AI readiness Step 1) ─────────────────────────────

    /// Open a live tracking session before the Operator starts the first step.
    /// Returns the liveSessionId — store it in @State and pass to all subsequent
    /// event pushes and to the final sign-off request.
    func openLiveGuideSession(
        guideId:      String,
        anchorId:     String,
        guideName:    String,
        anchorName:   String,
        operatorName: String,
        workContext:  String? = nil,          // Production # / audit name (K2)
        operatorEmail: String? = nil,
        operatorEmployeeId: String? = nil
    ) async throws -> String {
        struct Req: Encodable {
            let guideId, anchorId, guideName, anchorName, operatorName: String
            let workContext: String?
            let operatorEmail: String?
            let operatorEmployeeId: String?
        }
        struct LiveSession: Decodable { let id: String }
        struct Wrapper:     Decodable { let data: LiveSession }
        let body    = Req(guideId: guideId, anchorId: anchorId,
                          guideName: guideName, anchorName: anchorName,
                          operatorName: operatorName,
                          workContext: workContext,
                          operatorEmail: operatorEmail,
                          operatorEmployeeId: operatorEmployeeId)
        let wrapper = try await post(Wrapper.self, path: "/guide-sessions/live", body: body)
        return wrapper.data.id
    }

    /// Fire-and-forget: push a step event to the live session.
    /// Wrapped in Task{} by callers so the AR session is never blocked.
    func pushGuideSessionEvent(liveSessionId: String, event: PushGuideSessionEventRequest) async {
        struct Ack: Decodable {}   // we don't need the response body
        _ = try? await post(
            Ack.self,
            path: "/guide-sessions/live/\(liveSessionId)/events",
            body: event
        )
    }

    /// Poll for AI-generated hints for the current live session.
    /// Returns all pending hints and clears the server queue (consume-once).
    /// Returns [] silently on any network or decode error — never throws.
    func fetchGuideHints(liveSessionId: String) async -> [AIHint] {
        struct Wrapper: Decodable { let data: [AIHint] }
        guard let wrapper = try? await get(Wrapper.self,
                                           path: "/guide-sessions/live/\(liveSessionId)/hints") else {
            return []
        }
        return wrapper.data
    }

    // ── AR OMS — Guide Worldmaps ─────────────────────────────────────────────

    /// Author: upload the ARWorldMap captured during guide step placement.
    /// Also accepts an optional JPEG reference photo (base64) for Operator re-localization.
    /// 90s timeout — ARWorldMap blobs can be large.
    func uploadGuideWorldMap(guideId: String, mapData: Data, referencePhotoData: Data? = nil) async throws {
        struct Body: Encodable {
            let worldMapBase64:        String
            let capturedAt:            String
            let referencePhotoBase64:  String?
        }
        struct Resp: Decodable { let guideId: String; let sizeBytes: Int; let refPhotoSaved: Bool }
        let body = Body(
            worldMapBase64:       mapData.base64EncodedString(),
            capturedAt:           ISO8601DateFormatter().string(from: Date()),
            referencePhotoBase64: referencePhotoData?.base64EncodedString()
        )
        _ = try await post(Resp.self, path: "/worldmap/guide/\(guideId)/upload", body: body, timeout: 90)
    }

    /// Operator: download the ARWorldMap for a guide to re-localize the session.
    /// Returns nil on 404 (Author has not yet placed steps for this guide).
    func fetchGuideWorldMap(guideId: String) async throws -> Data? {
        var req = try makeRequest(method: "GET", path: "/worldmap/guide/\(guideId)")
        req.timeoutInterval = 45
        let (data, response): (Data, URLResponse)
        do { (data, response) = try await session.data(for: req) }
        catch { throw SIBClientError.networkError(error) }
        guard let http = response as? HTTPURLResponse else { return nil }
        if http.statusCode == 404 { return nil }
        if !(200...299).contains(http.statusCode) {
            throw SIBClientError.httpError(http.statusCode, "Guide world map download failed (\(http.statusCode))")
        }
        return data
    }

    /// Operator: download the reference photo for a guide's re-localization overlay.
    /// Returns nil on 404 (photo was not captured or Author skipped it).
    func fetchGuideWorldMapPhoto(guideId: String) async throws -> Data? {
        var req = try makeRequest(method: "GET", path: "/worldmap/guide/\(guideId)/photo")
        req.timeoutInterval = 20
        let (data, response): (Data, URLResponse)
        do { (data, response) = try await session.data(for: req) }
        catch { throw SIBClientError.networkError(error) }
        guard let http = response as? HTTPURLResponse else { return nil }
        if http.statusCode == 404 { return nil }
        if !(200...299).contains(http.statusCode) { return nil }
        return data
    }

    // ── 3D Model library ─────────────────────────────────────────────────────

    /// Fetch all models in an anchor's asset library (all statuses).
    /// Ordered newest-first by the server.
    func fetchModels(anchorId: String) async throws -> [Model3D] {
        try await get([Model3D].self, path: "/models?anchorId=\(anchorId)")
    }

    /// Fetch metadata for a single model — useful for polling conversion status.
    func fetchModel(id: String) async throws -> Model3D {
        try await get(Model3D.self, path: "/models/\(id)")
    }

    /// Download the GLB binary for a model.
    /// Returns raw Data; caller is responsible for writing to a cache file.
    /// 60s timeout — GLB files can be several MB.
    func downloadModelGLB(id: String) async throws -> Data {
        var req = try makeRequest(method: "GET", path: "/models/\(id)/file.glb")
        req.timeoutInterval = 60
        let (data, response): (Data, URLResponse)
        do { (data, response) = try await session.data(for: req) }
        catch { throw SIBClientError.networkError(error) }
        if let http = response as? HTTPURLResponse, !(200...299).contains(http.statusCode) {
            let msg = (try? JSONDecoder().decode(APIError.self, from: data))?.error
                ?? "HTTP \(http.statusCode)"
            throw SIBClientError.httpError(http.statusCode, msg)
        }
        return data
    }

    /// Download the USDZ binary for a model.
    /// Returns raw Data; caller writes to a cache file.
    /// 30s timeout — USDZ is typically smaller than GLB.
    func downloadModelUSDZ(id: String) async throws -> Data {
        var req = try makeRequest(method: "GET", path: "/models/\(id)/file.usdz")
        req.timeoutInterval = 30
        let (data, response): (Data, URLResponse)
        do { (data, response) = try await session.data(for: req) }
        catch { throw SIBClientError.networkError(error) }
        if let http = response as? HTTPURLResponse, !(200...299).contains(http.statusCode) {
            let msg = (try? JSONDecoder().decode(APIError.self, from: data))?.error
                ?? "HTTP \(http.statusCode)"
            throw SIBClientError.httpError(http.statusCode, msg)
        }
        return data
    }

    // ── .tag virtual emitter (spec: docs/TAG-FORMAT.md) ──────────────────────

    /// Raw part-level .tag envelope bytes. Caller verifies + caches via
    /// TagEnvelopeReader (raw bytes are kept so the cache re-verifies later).
    func fetchPartTagEnvelope(tagId: String) async throws -> Data {
        try await fetchRawEnvelope(path: "/tags/\(tagId)/emit")
    }

    /// Raw assembly-level (chamber) .tag envelope bytes.
    func fetchAssemblyTagEnvelope(anchorId: String) async throws -> Data {
        try await fetchRawEnvelope(path: "/anchors/\(anchorId)/emit")
    }

    private func fetchRawEnvelope(path: String) async throws -> Data {
        var req = try makeRequest(method: "GET", path: path)
        req.timeoutInterval = 20
        let (data, response): (Data, URLResponse)
        do { (data, response) = try await session.data(for: req) }
        catch { throw SIBClientError.networkError(error) }
        if let http = response as? HTTPURLResponse, !(200...299).contains(http.statusCode) {
            let msg = (try? JSONDecoder().decode(APIError.self, from: data))?.error ?? "HTTP \(http.statusCode)"
            throw SIBClientError.httpError(http.statusCode, msg)
        }
        return data
    }

    // ── HTTP helpers ──────────────────────────────────────────────────────────

    private func get<T: Decodable>(_ type: T.Type, path: String) async throws -> T {
        try await perform(makeRequest(method: "GET", path: path), decoding: type)
    }

    @discardableResult
    private func delete(path: String) async throws -> Data {
        let req = try makeRequest(method: "DELETE", path: path)
        let (data, response): (Data, URLResponse)
        do { (data, response) = try await session.data(for: req) }
        catch { throw SIBClientError.networkError(error) }
        if let http = response as? HTTPURLResponse, !(200...299).contains(http.statusCode) {
            let msg = (try? JSONDecoder().decode(APIError.self, from: data))?.error
                ?? String(data: data, encoding: .utf8) ?? "Unknown error"
            throw SIBClientError.httpError(http.statusCode, msg)
        }
        return data
    }

    private func post<B: Encodable, R: Decodable>(
        _ type: R.Type, path: String, body: B, timeout: TimeInterval? = nil
    ) async throws -> R {
        var req = try makeRequest(method: "POST", path: path)
        if let timeout { req.timeoutInterval = timeout } // #73: per-operation override
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
        return try await perform(req, decoding: type)
    }

    private func patch<B: Encodable, R: Decodable>(_ type: R.Type, path: String, body: B) async throws -> R {
        var req = try makeRequest(method: "PATCH", path: path)
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
        return try await perform(req, decoding: type)
    }

    private func perform<T: Decodable>(_ request: URLRequest, decoding type: T.Type) async throws -> T {
        let (data, response): (Data, URLResponse)
        do { (data, response) = try await session.data(for: request) }
        catch { throw SIBClientError.networkError(error) }

        if let http = response as? HTTPURLResponse, !(200...299).contains(http.statusCode) {
            let msg = (try? JSONDecoder().decode(APIError.self, from: data))?.error
                ?? String(data: data, encoding: .utf8) ?? "Unknown error"
            throw SIBClientError.httpError(http.statusCode, msg)
        }

        let decoder = JSONDecoder()
        if let envelope = try? decoder.decode(APIResponse<T>.self, from: data) { return envelope.data }
        do { return try decoder.decode(T.self, from: data) }
        catch { throw SIBClientError.decodingError(error) }
    }

    private func makeRequest(method: String, path: String) throws -> URLRequest {
        guard settings.isConfigured else { throw SIBClientError.notConfigured }
        let raw = settings.normalizedBaseURL + path
        guard let url = URL(string: raw) else { throw SIBClientError.invalidURL(raw) }
        var req = URLRequest(url: url)
        req.httpMethod = method
        // Phase 2.5 — API key auth: send X-API-Key on every request.
        // The SIB ignores this header when SIB_API_KEY env var is not set (local dev).
        let key = settings.apiKey.trimmingCharacters(in: .whitespaces)
        if !key.isEmpty {
            req.setValue(key, forHTTPHeaderField: "X-API-Key")
        }
        // UAM identity (RBAC): carried on EVERY request so the server can
        // enforce roles and per-user guide sharing. Empty until verified.
        if !settings.uamToken.isEmpty {
            req.setValue(settings.uamToken, forHTTPHeaderField: "X-User-Token")
        }
        return req
    }

    // ── UAM login (RBAC ahead of SSO) ─────────────────────────────────────────

    struct UamLoginUser: Codable {
        let email: String
        let name:  String
        let role:  String
    }
    struct UamLoginResult: Codable {
        let token: String
        let user:  UamLoginUser
    }
    private struct UamLoginEnvelope: Codable { let data: UamLoginResult }

    /// Verify identity against the server's allow-list. Both email and
    /// employee ID must match the UAM record. Throws httpError(401, …) when
    /// not listed / mismatched — callers surface the server's message.
    func uamLogin(email: String, employeeId: String) async throws -> UamLoginResult {
        try await uamLoginRaw(body: ["email": email, "employeeId": employeeId])
    }

    /// Kiosk path (2026.4.45): the employee ID alone identifies the technician.
    func uamLoginKiosk(employeeId: String) async throws -> UamLoginResult {
        try await uamLoginRaw(body: ["employeeId": employeeId])
    }

    /// True when the server's allow-list has users (GET /config.uamActive) —
    /// the signal that the kiosk start screen must gate the app.
    func uamActive() async throws -> Bool {
        var req = try makeRequest(method: "GET", path: "/config")
        req.timeoutInterval = 10
        let (data, _) = try await session.data(for: req)
        // NB: /config is FLAT (predates the {data:…} envelope convention) —
        // decode the top-level object directly.
        struct Cfg: Codable { let uamActive: Bool? }
        return (try JSONDecoder().decode(Cfg.self, from: data)).uamActive ?? false
    }

    private func uamLoginRaw(body: [String: String]) async throws -> UamLoginResult {
        var req = try makeRequest(method: "POST", path: "/uam/login")
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
        req.timeoutInterval = 15
        let (data, response): (Data, URLResponse)
        do { (data, response) = try await session.data(for: req) }
        catch { throw SIBClientError.networkError(error) }
        if let http = response as? HTTPURLResponse, !(200...299).contains(http.statusCode) {
            let msg = (try? JSONDecoder().decode(APIError.self, from: data))?.error ?? "HTTP \(http.statusCode)"
            throw SIBClientError.httpError(http.statusCode, msg)
        }
        return try JSONDecoder().decode(UamLoginEnvelope.self, from: data).data
    }
}
