// SIBClient.swift — Phase 2A
// async/await REST client for SIB v0.2. All network calls go through here.

import Foundation

enum SIBClientError: LocalizedError {
    case notConfigured
    case invalidURL(String)
    case networkError(Error)
    case httpError(Int, String)
    case decodingError(Error)

    var errorDescription: String? {
        switch self {
        case .notConfigured:          return "SIB URL not configured. Go to Settings."
        case .invalidURL(let u):      return "Invalid URL: \(u)"
        case .networkError(let e):    return "Network error: \(e.localizedDescription)"
        case .httpError(let c, let m): return "SIB error \(c): \(m)"
        case .decodingError(let e):   return "Bad response: \(e.localizedDescription)"
        }
    }
}

final class SIBClient {

    private let settings: AppSettings
    private let session: URLSession

    init(settings: AppSettings) {
        self.settings = settings
        let config = URLSessionConfiguration.default
        config.timeoutIntervalForRequest = 60   // validate-all runs SSIM on many tags
        self.session = URLSession(configuration: config)
    }

    // ── Connection ────────────────────────────────────────────────────────────

    func testConnection() async throws {
        _ = try await get([Anchor].self, path: "/anchors")
    }

    // ── Anchors ───────────────────────────────────────────────────────────────

    /// List all anchors — used by AnchorDirectoryView.
    func fetchAnchors() async throws -> [Anchor] {
        try await get([Anchor].self, path: "/anchors")
    }

    func fetchAnchor(id: String) async throws -> Anchor {
        try await get(Anchor.self, path: "/anchors/\(id)")
    }

    /// Phase 2.5 G1 — check whether an anchor has enough trained pass-states for Operator use.
    func fetchAnchorReadiness(id: String) async throws -> AnchorReadiness {
        try await get(AnchorReadiness.self, path: "/anchors/\(id)/readiness")
    }

    func createAnchor(_ req: CreateAnchorRequest) async throws -> Anchor {
        try await post(Anchor.self, path: "/anchors", body: req)
    }

    /// Delete an anchor and all its tags + pass-states (cascade).
    func deleteAnchor(id: String) async throws {
        try await delete(path: "/anchors/\(id)")
    }

    /// Fetch the canonical QR PNG generated by the server at anchor creation.
    /// Both the iOS app (QRGeneratorView) and the portal display this image so
    /// all clients show the identical pixel pattern regardless of QR library.
    func fetchAnchorQRImage(anchorId: String) async throws -> Data {
        let req = try makeRequest(method: "GET", path: "/anchors/\(anchorId)/qrimage")
        let (data, response): (Data, URLResponse)
        do { (data, response) = try await session.data(for: req) }
        catch { throw SIBClientError.networkError(error) }
        if let http = response as? HTTPURLResponse, !(200...299).contains(http.statusCode) {
            let msg = (try? JSONDecoder().decode(APIError.self, from: data))?.error ?? "HTTP \(http.statusCode)"
            throw SIBClientError.httpError(http.statusCode, msg)
        }
        return data
    }

    /// Upload a serialised ARWorldMap (NSKeyedArchiver binary plist) for an anchor.
    /// The server stores it so subsequent sessions can relocalize into the same
    /// feature-point cloud, giving scan-position-independent tag placement.
    func uploadWorldMap(anchorId: String, data: Data) async throws {
        var req = try makeRequest(method: "POST", path: "/anchors/\(anchorId)/worldmap")
        req.setValue("application/octet-stream", forHTTPHeaderField: "Content-Type")
        req.httpBody = data
        let (_, response): (Data, URLResponse)
        do { (_, response) = try await session.data(for: req) }
        catch { throw SIBClientError.networkError(error) }
        if let http = response as? HTTPURLResponse, !(200...299).contains(http.statusCode) {
            throw SIBClientError.httpError(http.statusCode, "World map upload failed (\(http.statusCode))")
        }
    }

    /// Download a previously stored ARWorldMap binary for an anchor.
    /// Returns nil (does NOT throw) on 404 — meaning no map has been saved yet
    /// and the caller should start a fresh session instead.
    func fetchWorldMap(anchorId: String) async throws -> Data? {
        let req = try makeRequest(method: "GET", path: "/anchors/\(anchorId)/worldmap")
        let (data, response): (Data, URLResponse)
        do { (data, response) = try await session.data(for: req) }
        catch { throw SIBClientError.networkError(error) }
        guard let http = response as? HTTPURLResponse else { return nil }
        if http.statusCode == 404 { return nil }            // no map stored yet — normal first-session case
        if !(200...299).contains(http.statusCode) {
            throw SIBClientError.httpError(http.statusCode, "World map download failed (\(http.statusCode))")
        }
        return data
    }

    // ── Tags ──────────────────────────────────────────────────────────────────

    func fetchTags(anchorId: String) async throws -> [Tag] {
        try await get([Tag].self, path: "/tags?anchorId=\(anchorId)")
    }

    func createTag(_ req: CreateTagRequest) async throws -> Tag {
        try await post(Tag.self, path: "/tags", body: req)
    }

    func updateTag(id: String, req: UpdateTagRequest) async throws -> Tag {
        try await patch(Tag.self, path: "/tags/\(id)", body: req)
    }

    func deleteTag(id: String) async throws {
        try await delete(path: "/tags/\(id)")
    }

    func deleteAllTags(anchorId: String) async throws {
        try await delete(path: "/tags?anchorId=\(anchorId)")
    }

    // ── Pass-state ────────────────────────────────────────────────────────────

    func trainPassState(_ req: CreatePassStateRequest) async throws {
        struct R: Codable { let id: String }
        _ = try await post(R.self, path: "/perception/train", body: req)
    }

    func fetchPassState(tagId: String) async throws -> PassState {
        try await get(PassState.self, path: "/perception/pass-state/\(tagId)")
    }

    // ── Validation ────────────────────────────────────────────────────────────

    func validateAll(_ req: BatchValidateRequest) async throws -> AnchorValidationResult {
        try await post(AnchorValidationResult.self, path: "/perception/validate-all", body: req)
    }

    // ── Sessions ──────────────────────────────────────────────────────────────

    func createSession(userId: String, assetId: String) async throws -> SIBSession {
        try await post(SIBSession.self, path: "/sessions",
                       body: CreateSessionRequest(userId: userId, assetId: assetId))
    }

    // ── HTTP helpers ──────────────────────────────────────────────────────────

    private func get<T: Decodable>(_ type: T.Type, path: String) async throws -> T {
        try await perform(makeRequest(method: "GET", path: path), decoding: type)
    }

    @discardableResult
    private func delete(path: String) async throws -> Data {
        let req = try makeRequest(method: "DELETE", path: path)
        let (data, response): (Data, URLResponse)
        do { (data, response) = try await session.data(for: req) }
        catch { throw SIBClientError.networkError(error) }
        if let http = response as? HTTPURLResponse, !(200...299).contains(http.statusCode) {
            let msg = (try? JSONDecoder().decode(APIError.self, from: data))?.error
                ?? String(data: data, encoding: .utf8) ?? "Unknown error"
            throw SIBClientError.httpError(http.statusCode, msg)
        }
        return data
    }

    private func post<B: Encodable, R: Decodable>(_ type: R.Type, path: String, body: B) async throws -> R {
        var req = try makeRequest(method: "POST", path: path)
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
        return try await perform(req, decoding: type)
    }

    private func patch<B: Encodable, R: Decodable>(_ type: R.Type, path: String, body: B) async throws -> R {
        var req = try makeRequest(method: "PATCH", path: path)
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
        return try await perform(req, decoding: type)
    }

    private func perform<T: Decodable>(_ request: URLRequest, decoding type: T.Type) async throws -> T {
        let (data, response): (Data, URLResponse)
        do { (data, response) = try await session.data(for: request) }
        catch { throw SIBClientError.networkError(error) }

        if let http = response as? HTTPURLResponse, !(200...299).contains(http.statusCode) {
            let msg = (try? JSONDecoder().decode(APIError.self, from: data))?.error
                ?? String(data: data, encoding: .utf8) ?? "Unknown error"
            throw SIBClientError.httpError(http.statusCode, msg)
        }

        let decoder = JSONDecoder()
        if let envelope = try? decoder.decode(APIResponse<T>.self, from: data) { return envelope.data }
        do { return try decoder.decode(T.self, from: data) }
        catch { throw SIBClientError.decodingError(error) }
    }

    private func makeRequest(method: String, path: String) throws -> URLRequest {
        guard settings.isConfigured else { throw SIBClientError.notConfigured }
        let raw = settings.normalizedBaseURL + path
        guard let url = URL(string: raw) else { throw SIBClientError.invalidURL(raw) }
        var req = URLRequest(url: url)
        req.httpMethod = method
        // Phase 2.5 — API key auth: send X-API-Key on every request.
        // The SIB ignores this header when SIB_API_KEY env var is not set (local dev).
        let key = settings.apiKey.trimmingCharacters(in: .whitespaces)
        if !key.isEmpty {
            req.setValue(key, forHTTPHeaderField: "X-API-Key")
        }
        return req
    }
}
