#!/usr/bin/env node
// arch-graph.mjs - level 4 of docs/ARCHITECTURE.md, generated from the code.
//
//   npm run arch:graph   writes docs/architecture/deps.json, deps-sib.mmd, deps-app.mmd
//   npm run arch:check   regenerates in memory and fails if the committed files differ
//
// SIB: every `import ... from './x.js'` in sib/src (relative imports only;
// packages are not architecture). iOS: every Swift file's top-level type
// names, then every other file that mentions one of them. Both reduce to a
// folder-level Mermaid graph with edge counts, and a per-file JSON the
// /architecture page uses for "what does X depend on".
//
// Deterministic output (sorted everywhere) so a diff is a real change.

import { readFileSync, readdirSync, statSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'docs', 'architecture');
const check = process.argv.includes('--check');

function walk(dir, ext, acc = []) {
  for (const name of readdirSync(dir).sort()) {
    const p = join(dir, name);
    if (name === 'node_modules' || name === 'dist' || name.startsWith('.')) continue;
    if (statSync(p).isDirectory()) walk(p, ext, acc);
    else if (name.endsWith(ext)) acc.push(p);
  }
  return acc;
}
const posix = p => p.split(sep).join('/');
const folderOf = rel => { const parts = rel.split('/'); return parts.length > 1 ? parts.slice(0, -1).join('/') : '.'; };

// ── SIB (TypeScript) ───────────────────────────────────────────────────────
function scanSib() {
  const base = join(ROOT, 'sib', 'src');
  const files = walk(base, '.ts').filter(f => !f.endsWith('.d.ts'));
  const deps = {};
  for (const f of files) {
    const rel = posix(relative(base, f));
    const src = readFileSync(f, 'utf8');
    const out = new Set();
    const re = /(?:import|export)\s[^'"]*?from\s+['"](\.{1,2}\/[^'"]+)['"]|import\s*\(\s*['"](\.{1,2}\/[^'"]+)['"]\s*\)|import\s+['"](\.{1,2}\/[^'"]+)['"]/g;
    let m;
    while ((m = re.exec(src))) {
      const spec = m[1] || m[2] || m[3];
      let target = posix(join(dirname(rel), spec)).replace(/\.js$/, '.ts');
      if (!target.endsWith('.ts')) target += '.ts';
      if (target.startsWith('../')) { out.add('@' + spec.replace(/^(\.\.\/)+/, '')); continue; }   // outside sib/src (shared/)
      out.add(target);
    }
    deps[rel] = [...out].sort();
  }
  return deps;
}

// ── iOS (Swift) ────────────────────────────────────────────────────────────
function scanApp() {
  const base = join(ROOT, 'ios-app', 'SpatialTaggingApp', 'SpatialTaggingApp');
  if (!existsSync(base)) return {};
  const files = walk(base, '.swift');
  const declared = new Map();                       // type name → file
  const sources = new Map();
  const declRe = /^\s*(?:@\w+(?:\([^)]*\))?\s+)*(?:public\s+|internal\s+|private\s+|fileprivate\s+|final\s+|indirect\s+)*(?:struct|class|enum|actor|protocol)\s+([A-Z][A-Za-z0-9_]*)/gm;
  for (const f of files) {
    const rel = posix(relative(base, f));
    const src = readFileSync(f, 'utf8');
    sources.set(rel, src);
    let m;
    while ((m = declRe.exec(src))) if (!declared.has(m[1])) declared.set(m[1], rel);
  }
  const deps = {};
  const names = [...declared.keys()].sort((a, b) => b.length - a.length);
  const wordRe = new RegExp('\\b(' + names.map(n => n.replace(/[$]/g, '\\$')).join('|') + ')\\b', 'g');
  for (const [rel, src] of sources) {
    const out = new Set();
    // Strip comments and string literals so a mention in prose does not count.
    const code = src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '').replace(/"(?:[^"\\]|\\.)*"/g, '""');
    let m;
    while ((m = wordRe.exec(code))) { const t = declared.get(m[1]); if (t && t !== rel) out.add(t); }
    deps[rel] = [...out].sort();
  }
  return deps;
}

// ── Folder-level Mermaid ───────────────────────────────────────────────────
function folderGraph(deps, title) {
  const edges = new Map();
  const folders = new Set();
  for (const [file, targets] of Object.entries(deps)) {
    const a = folderOf(file); folders.add(a);
    for (const t of targets) {
      if (t.startsWith('@')) { folders.add('shared'); bump(edges, a, 'shared'); continue; }
      const b = folderOf(t); folders.add(b);
      if (a !== b) bump(edges, a, b);
    }
  }
  const id = f => 'F_' + f.replace(/[^A-Za-z0-9]/g, '_');
  const counts = {};
  for (const f of Object.keys(deps)) counts[folderOf(f)] = (counts[folderOf(f)] || 0) + 1;
  let s = `%% generated by scripts/arch-graph.mjs - do not edit\nflowchart LR\n  %% ${title}\n`;
  for (const f of [...folders].sort()) s += `  ${id(f)}["${f === '.' ? '(root)' : f}${counts[f] ? ` · ${counts[f]} files` : ''}"]\n`;
  for (const [k, n] of [...edges.entries()].sort()) { const [a, b] = k.split('\u0000'); s += `  ${id(a)} -->|${n}| ${id(b)}\n`; }
  return s;
}
function bump(map, a, b) { const k = a + '\u0000' + b; map.set(k, (map.get(k) || 0) + 1); }

// ── Run ────────────────────────────────────────────────────────────────────
const sib = scanSib(), app = scanApp();
const json = JSON.stringify({ generatedBy: 'scripts/arch-graph.mjs', sib, app }, null, 1) + '\n';
const outputs = {
  'deps.json': json,
  'deps-sib.mmd': folderGraph(sib, 'sib/src - relative imports between folders (edge label = number of imports)'),
  'deps-app.mmd': folderGraph(app, 'ios-app - type references between folders (edge label = number of references)'),
};

if (check) {
  let drift = 0;
  for (const [name, content] of Object.entries(outputs)) {
    const p = join(OUT, name);
    const have = existsSync(p) ? readFileSync(p, 'utf8') : '';
    if (have !== content) { drift++; console.error(`✗ docs/architecture/${name} is out of date - run npm run arch:graph`); }
  }
  if (drift) process.exit(1);
  console.log(`✓ arch-check: docs/architecture/ matches the code (${Object.keys(sib).length} ts files, ${Object.keys(app).length} swift files)`);
} else {
  mkdirSync(OUT, { recursive: true });
  for (const [name, content] of Object.entries(outputs)) writeFileSync(join(OUT, name), content);
  console.log(`wrote docs/architecture/ - ${Object.keys(sib).length} ts files, ${Object.keys(app).length} swift files`);
}
